'use client';
import { FormEvent, useEffect, useState } from 'react';
import { buyerPortalApi } from '@/lib/api';
export default function BuyerPage() {
  const [data, setData] = useState<any>(null); const [reference, setReference] = useState(''); const [trace, setTrace] = useState<any>(null); const [error, setError] = useState('');
  useEffect(() => { buyerPortalApi.dashboard().then((r) => setData(r.data)).catch(() => setError('Unable to load buyer dashboard.')); }, []);
  const lookup = async (e: FormEvent) => { e.preventDefault(); setError(''); try { setTrace((await buyerPortalApi.traceability(reference)).data); } catch { setTrace(null); setError('No completed sale was found for that invoice, Lot, or tracking code.'); } };
  return <div><h1 style={{ fontFamily: 'Outfit, sans-serif', fontSize: 26, fontWeight: 800 }}>Buyer Portal</h1><p style={{ color: 'var(--neutral-500)', margin: '8px 0 24px' }}>Aggregate MAYODE production and privacy-safe traceability indicators.</p>{error && <p style={{ color: 'var(--red-400)' }}>{error}</p>}{!data ? <p>Loading…</p> : <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit,minmax(210px,1fr))', gap: 16 }}>{[['Farmers', data.totalFarmers], ['Hectares', data.totalHectares], ['Yield / ha', `${Math.round(data.averageYieldPerHectare)} kg`], ['Revenue', `TZS ${Math.round(data.totalRevenue).toLocaleString()}`]].map(([label, value]) => <div key={String(label)} className="stat-card" style={{ padding: 22 }}><div style={{ color: 'var(--neutral-500)' }}>{label}</div><strong style={{ display: 'block', fontSize: 24, marginTop: 8 }}>{value}</strong></div>)}</div>}<form onSubmit={lookup} className="glass-card" style={{ padding: 20, marginTop: 24, display: 'flex', gap: 10 }}><input value={reference} onChange={(e) => setReference(e.target.value)} required placeholder="Invoice, Lot, or inventory tracking code" style={{ flex: 1, padding: 10 }} /><button type="submit" style={{ background: 'var(--accent)', color: '#fff', border: 0, borderRadius: 8, padding: '10px 16px' }}>Trace</button></form>{trace && <div className="glass-card" style={{ padding: 20, marginTop: 16 }}><strong>{trace.invoiceNumber} · {trace.lot.lotNumber}</strong><p style={{ color: 'var(--neutral-500)' }}>{trace.sourceRecords.length} source inventory records · {trace.lot.totalWeightKg.toLocaleString()} kg</p><div style={{ display: 'grid', gap: 8 }}>{trace.sourceRecords.map((record: any) => <div key={record.trackingCode} style={{ padding: 10, background: 'var(--surface-tint)', borderRadius: 8 }}>{record.trackingCode} · {record.weightKg} kg · {record.qualityGrade || 'Ungraded'} · {record.region || 'Region not recorded'}</div>)}</div></div>}</div>;
}
