'use client';
import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { EmptyState, InsightPanel, money } from '@/components/role-dashboards/DashboardPrimitives';
import FarmerLandListingForm from '@/components/marketplace/FarmerLandListingForm';
import { marketplaceApi, API_BASE_URL } from '@/lib/api';
import { apiError } from '@/lib/download';
import { useFarmerData } from '../FarmerDataContext';

export default function FarmerMarketplacePage() {
  const { farmer, farms, landListings, tractors, reload } = useFarmerData();
  const [mine, setMine] = useState<any[]>([]); const [bookings, setBookings] = useState<any[]>([]);
  const [selected, setSelected] = useState<any>(null); const [offers, setOffers] = useState<any[]>([]); const [schedule, setSchedule] = useState<any>(null); const [quote, setQuote] = useState<any>(null);
  const [bid, setBid] = useState(''); const [phone, setPhone] = useState(''); const [search, setSearch] = useState('');
  const [tractorId, setTractorId] = useState(''); const [hectares, setHectares] = useState(''); const [terrain, setTerrain] = useState('B'); const [date, setDate] = useState('');
  const [improvement, setImprovement] = useState(''); const [cost, setCost] = useState(''); const [subPrice, setSubPrice] = useState('');
  const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => { setLoading(true); try { const [m, b] = await Promise.all([marketplaceApi.managedListings(), marketplaceApi.myTractorBookings()]); setMine(m.data); setBookings(b.data); } catch (e) { setError(apiError(e)); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const inspect = async (listing: any) => {
    setSelected(listing); setOffers([]); setSchedule(null); setQuote(null); setError(''); setBid('');
    try {
      const [o, s, q] = await Promise.all([marketplaceApi.getOffers(listing.id), listing.isMultiYear ? marketplaceApi.getRentSchedule(listing.id) : Promise.resolve(null), listing.ownerId !== farmer?.id && listing.leaseStatus === 'DRAFT' ? marketplaceApi.depositQuote(listing.id) : Promise.resolve(null)]);
      setOffers(o.data); setSchedule(s?.data ?? null); setQuote(q?.data ?? null);
    } catch (e) { setError(apiError(e)); }
  };
  async function action(fn: () => Promise<unknown>, success: string) {
    if (busy) return; setBusy(true); setError(''); setMessage('');
    try { await fn(); setMessage(success); setSelected(null); await Promise.all([load(), reload()]); }
    catch (e) { setError(apiError(e)); } finally { setBusy(false); }
  }
  const available = landListings.filter((l) => l.leaseStatus === 'DRAFT' && `${l.farm?.farmCode} ${l.farm?.village} ${l.dealType}`.toLowerCase().includes(search.toLowerCase()));
  const isOwner = selected?.ownerId === farmer?.id; const isRenter = selected?.renterId === farmer?.id;
  async function book(e: FormEvent) { e.preventDefault(); await action(() => marketplaceApi.bookTractor({ tractorId, farmerId: farmer.id, hectares: Number(hectares), terrainGrade: terrain, scheduledDate: new Date(date).toISOString() }), 'Tractor booking requested.'); }
  return <div className="page-shell"><h1 className="page-title">M-LAX Marketplace</h1><p className="page-subtitle">Find land, manage your rentals, negotiate offers, and book tractor services.</p>
    {error && <div role="alert" className="alert-box alert-danger">{error}</div>}{message && <div role="status" className="alert-box alert-success">{message}</div>}
    <fieldset disabled={busy} style={{ border: 0, padding: 0, minWidth: 0, display: 'grid', gap: 20 }}>
      <div className="role-two-col"><InsightPanel title="Available land"><label className="form-label">Search farm, village or deal<input className="input-field" value={search} onChange={(e) => setSearch(e.target.value)} /></label><div className="role-list">{available.map((l) => <div className="role-list-item" key={l.id}><div><strong>{l.farm?.farmCode}</strong><p>{money(l.askingPrice)} · {l.leaseDurationMonths} months · {l.dealType}</p><p>{l.farm?.socialHectares} ha · {l.farm?.actualAcres ?? '—'} actual acres · Grade {l.farm?.grade}</p></div><button className="btn-secondary" onClick={() => void inspect(mine.find((m) => m.id === l.id) ?? l)}>View terms</button></div>)}{!available.length && <EmptyState>No available land matches your search.</EmptyState>}</div></InsightPanel>
      <InsightPanel title="My listings and rentals">{loading ? <p>Loading rentals…</p> : <div className="role-list">{mine.map((l) => <div className="role-list-item" key={l.id}><div><strong>{l.farm?.farmCode}</strong><p>{l.ownerId === farmer?.id ? 'Landowner' : 'Renter'} · {l.leaseStatus}</p><p>{l.leaseEndDate ? `Until ${l.leaseEndDate.slice(0, 10)}` : `${l.leaseDurationMonths} months`}</p></div><button className="btn-secondary" onClick={() => void inspect(l)}>Manage</button></div>)}{!mine.length && <EmptyState>No listings or rentals yet.</EmptyState>}</div>}</InsightPanel></div>
      {selected && <InsightPanel title={`Rental details · ${selected.farm?.farmCode}`} subtitle={`${selected.leaseStatus} · ${money(selected.askingPrice)} · ${selected.leaseDurationMonths} months`}>
        <button className="btn-secondary" onClick={() => setSelected(null)}>Close details</button>
        {selected.agreementPdfUrl && <a className="btn-secondary" href={new URL(selected.agreementPdfUrl, API_BASE_URL.replace(/\/api\/v1\/?$/, '')).href} target="_blank" rel="noreferrer">Open lease agreement</a>}
        <p>{selected.mayodeProtected ? 'MAYODE internal protection is recorded for this lease.' : 'Protection begins after confirmed payment and verification.'} This status is separate from an insurance policy.</p>
        {schedule && <div className="table-wrap"><table><thead><tr><th>Year</th><th>Rent</th><th>Status</th></tr></thead><tbody>{schedule.years.map((y: any) => <tr key={y.year}><td>{y.year}</td><td>{money(y.amount)}</td><td>{y.paid ? 'Paid' : 'Due'}</td></tr>)}</tbody></table></div>}
        {selected.leaseStatus === 'DRAFT' && !isOwner && <form className="form-grid" onSubmit={(e) => { e.preventDefault(); void action(() => marketplaceApi.submitOffer(selected.id, { farmerId: farmer.id, offerAmount: Number(bid) }), 'Offer submitted.'); }}><label className="form-label">Your offer (TZS)<input className="input-field" required type="number" min="1" value={bid} onChange={(e) => setBid(e.target.value)} /></label><button className="btn-secondary">Make an offer</button></form>}
        <div className="role-list">{offers.map((o) => <div className="role-list-item" key={o.id}><div><strong>{money(o.offerAmount)}</strong><p>{o.status}{o.counterAmount ? ` · Counter ${money(o.counterAmount)}` : ''}</p></div>
          {isOwner && o.status === 'PENDING' && <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}><button className="btn-secondary" onClick={() => void action(() => marketplaceApi.respondToOffer(selected.id, o.id, { ownerId: farmer.id, action: 'accept' }), 'Offer accepted.')}>Accept</button><button className="btn-secondary" onClick={() => void action(() => marketplaceApi.respondToOffer(selected.id, o.id, { ownerId: farmer.id, action: 'reject' }), 'Offer declined.')}>Decline</button><button className="btn-secondary" onClick={() => { const value = window.prompt('Counter-offer in TZS'); if (value && Number(value) > 0) void action(() => marketplaceApi.respondToOffer(selected.id, o.id, { ownerId: farmer.id, action: 'counter', counterAmount: Number(value) }), 'Counter-offer sent.'); }}>Counter</button></div>}
          {!isOwner && o.farmerId === farmer?.id && o.status === 'COUNTERED' && <div><button className="btn-secondary" onClick={() => void action(() => marketplaceApi.respondToCounter(selected.id, o.id, { farmerId: farmer.id, accept: true }), 'Counter-offer accepted.')}>Accept counter</button><button className="btn-secondary" onClick={() => void action(() => marketplaceApi.respondToCounter(selected.id, o.id, { farmerId: farmer.id, accept: false }), 'Counter-offer declined.')}>Decline counter</button></div>}
        </div>)}</div>
        {quote && !isOwner && <form className="form-grid" onSubmit={(e) => { e.preventDefault(); if (window.confirm(`Request payment of ${money(quote.amount)} to secure this rental? Approve the payment on your phone.`)) void action(() => marketplaceApi.depositEscrow(selected.id, { renterId: farmer.id, amount: quote.amount, phoneNumber: phone }), 'Payment requested. Approve on your phone, then refresh payment status.'); }}><p>Current deposit quote: <strong>{money(quote.amount)}</strong> · {quote.paymentPlan}{!quote.onlinePaymentsAvailable && ' · Online payments are not configured. Contact the cooperative.'}</p><label className="form-label">Mobile-money phone<input className="input-field" required type="tel" value={phone} onChange={(e) => setPhone(e.target.value)} /></label><button className="btn-primary" disabled={!quote.onlinePaymentsAvailable}>Request rental payment</button></form>}
        {(isOwner || isRenter) && selected.leaseStatus === 'PENDING_VERIFICATION' && <button className="btn-secondary" onClick={() => void action(() => marketplaceApi.reconcileEscrow(selected.id), 'Payment status refreshed; check the lease status.')}>Refresh payment status</button>}
        {isOwner && selected.leaseStatus === 'DRAFT' && <button className="btn-secondary" onClick={() => { if (window.confirm('Cancel this land listing?')) void action(() => marketplaceApi.cancelLandListing(selected.id), 'Listing cancelled.'); }}>Cancel listing</button>}
        {isRenter && selected.leaseStatus === 'ACTIVE' && <form className="form-grid" onSubmit={(e) => { e.preventDefault(); void action(() => marketplaceApi.requestSubLease(selected.id, { renterId: farmer.id, newAskingPrice: Number(subPrice) }), 'Sub-lease request sent to the owner.'); }}><label className="form-label">Sub-lease asking price (TZS)<input className="input-field" required type="number" min="1" value={subPrice} onChange={(e) => setSubPrice(e.target.value)} /></label><button className="btn-secondary">Request sub-lease</button></form>}
        {isOwner && selected.subLeases?.map((s: any) => <div key={s.id}><p>Sub-lease requested: {money(s.newAskingPrice)}</p><button className="btn-secondary" onClick={() => void action(() => marketplaceApi.approveSubLease(selected.id, s.id, { ownerId: farmer.id, approve: true }), 'Sub-lease approved.')}>Approve</button><button className="btn-secondary" onClick={() => void action(() => marketplaceApi.approveSubLease(selected.id, s.id, { ownerId: farmer.id, approve: false }), 'Sub-lease declined.')}>Decline</button></div>)}
        {isRenter && selected.leaseStatus === 'ACTIVE' && selected.isMultiYear && selected.paymentPlan === 'ANNUAL' && <><form className="form-grid" onSubmit={(e) => { e.preventDefault(); void action(() => marketplaceApi.logImprovement(selected.id, { renterId: farmer.id, description: improvement, amountTzs: Number(cost) }), 'Land improvement recorded.'); }}><label className="form-label">Land improvement<textarea className="input-field" required value={improvement} onChange={(e) => setImprovement(e.target.value)} /></label><label className="form-label">Cost (TZS)<input className="input-field" required type="number" min="1" value={cost} onChange={(e) => setCost(e.target.value)} /></label><button className="btn-secondary">Record improvement</button></form><button className="btn-secondary" onClick={() => { if (window.confirm('Request payment of the next annual installment using your registered phone?')) void action(() => marketplaceApi.payInstallment(selected.id, { renterId: farmer.id }), 'Installment payment requested. Confirm it on your phone.'); }}>Pay next installment</button></>}
      </InsightPanel>}
      <FarmerLandListingForm farms={farms} farmerId={farmer?.id} onSubmit={(data) => action(() => marketplaceApi.createLandListing(data), 'Land listing created.')} />
      <div className="role-two-col"><InsightPanel title="Book a tractor"><form className="form-grid" onSubmit={book}><label className="form-label">Tractor<select className="input-field" required value={tractorId} onChange={(e) => setTractorId(e.target.value)}><option value="">Select available tractor</option>{tractors.filter((t) => t.isAvailable).map((t) => <option key={t.id} value={t.id}>{t.model || t.registrationNo} · {money(t.pricePerHectare)} / ha</option>)}</select></label><label className="form-label">Area (hectares)<input className="input-field" required type="number" min="0.1" step="0.1" value={hectares} onChange={(e) => setHectares(e.target.value)} /></label><label className="form-label">Terrain<select className="input-field" value={terrain} onChange={(e) => setTerrain(e.target.value)}><option value="A">A — Flat</option><option value="B">B — Some obstacles</option><option value="C">C — Difficult terrain</option></select></label><label className="form-label">Service date<input className="input-field" required type="datetime-local" min={new Date().toISOString().slice(0, 16)} value={date} onChange={(e) => setDate(e.target.value)} /></label><p>Terrain surcharges and platform fees are calculated by the server and shown on your booking.</p><button className="btn-primary" disabled={!farmer}>Request booking</button></form></InsightPanel>
      <InsightPanel title="My tractor bookings"><div className="role-list">{bookings.map((b) => <div className="role-list-item" key={b.id}><div><strong>{b.tractor?.model || b.tractor?.registrationNo}</strong><p>{new Date(b.scheduledDate).toLocaleString()} · {b.hectares} ha · {money(b.totalPrice)} · {b.status}</p>{b.status === 'PENDING' && <button className="btn-secondary" onClick={() => void action(() => marketplaceApi.cancelTractorBooking(b.id), 'Booking cancelled.')}>Cancel booking</button>}{['CONFIRMED', 'IN_PROGRESS'].includes(b.status) && <button className="btn-secondary" onClick={() => { if (window.confirm('Confirm the tractor work has been completed satisfactorily?')) void action(() => marketplaceApi.completeTractorBooking(b.id), 'Service completion recorded.'); }}>Confirm work completed</button>}</div></div>)}{!bookings.length && <EmptyState>No tractor bookings yet.</EmptyState>}</div></InsightPanel></div>
    </fieldset>
  </div>;
}
